# Generated by Django 5.1 on 2024-09-12 01:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='make_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
