# Generated by Django 5.1 on 2024-09-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditems',
            name='price',
            field=models.DecimalField(decimal_places=0, default=None, max_digits=9),
        ),
    ]
