# Generated by Django 5.1 on 2024-09-11 05:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_ordereditems_price'),
        ('shop', '0003_product_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_amount',
            new_name='order_cost',
        ),
        migrations.CreateModel(
            name='Ordereditem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_price', models.DecimalField(decimal_places=0, max_digits=9)),
                ('order_quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Ordereditems',
        ),
    ]
